# Generated by Django 5.0.6 on 2024-06-14 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeName', models.CharField(max_length=255, verbose_name='Расположение места')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('timeWork', models.CharField(max_length=255, verbose_name='Время работы')),
                ('imgPoster', models.ImageField(upload_to='foods', verbose_name='Фото')),
                ('id_place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.places', verbose_name='Место')),
            ],
            options={
                'verbose_name': 'Еда',
                'verbose_name_plural': 'Еда',
            },
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('timeWork', models.CharField(max_length=255, verbose_name='Время работы')),
                ('imgPoster', models.ImageField(upload_to='shops', verbose_name='Фото')),
                ('id_place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.places', verbose_name='Место')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
    ]
