# Generated by Django 4.2.5 on 2023-10-09 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('showNews', models.CharField(choices=[('SHOW', 'Показать'), ('HIDE', 'Скрыть')], max_length=8, verbose_name='Показать новость')),
                ('imgPoster', models.ImageField(blank=True, upload_to='', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Карусель новостей',
                'verbose_name_plural': 'Карусель новостей',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('dateTime', models.DateTimeField(verbose_name='Дата/Время')),
                ('imgPoster', models.ImageField(upload_to='news', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel News', verbose_name='Фото')),
                ('carousel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.carouselnews', verbose_name='Карусель')),
            ],
            options={
                'verbose_name': 'Карусель новостей(фото)',
                'verbose_name_plural': 'Карусель новостей(фото)',
            },
        ),
    ]
