# Generated by Django 5.0.6 on 2024-05-29 15:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('imgPoster', models.ImageField(upload_to='news', verbose_name='Фото')),
                ('dateTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата/Время')),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='CarouselNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showNews', models.CharField(choices=[('SHOW', 'Показать'), ('HIDE', 'Скрыть')], max_length=8, verbose_name='Показать новость')),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.news', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Карусель новостей',
                'verbose_name_plural': 'Карусель новостей',
            },
        ),
    ]
