# Generated by Django 4.2.5 on 2023-10-09 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airlines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameAirlines', models.CharField(max_length=255, verbose_name='Название авиакомпании')),
                ('numberPhoneOne', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('numberPhoneTwo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Сайт')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('logoBig', models.ImageField(upload_to='logo Airlines', verbose_name='Большой логотип')),
                ('logoSmall', models.ImageField(blank=True, null=True, upload_to='logo Airlines', verbose_name='Маленький логотип')),
            ],
            options={
                'verbose_name': 'Авиакомпания',
                'verbose_name_plural': 'Авиакомпании',
            },
        ),
        migrations.CreateModel(
            name='Directions',
            fields=[
                ('country', models.CharField(max_length=255, verbose_name='Страна')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('nameAirport', models.CharField(max_length=255, verbose_name='Аэропорт')),
                ('utc', models.IntegerField(verbose_name='Часовой пояс')),
                ('IATA', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='IATA код')),
                ('ICAO', models.CharField(max_length=255, unique=True, verbose_name='ICAO код')),
                ('coordinates', models.CharField(max_length=255, verbose_name='Координаты')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
            },
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeName', models.CharField(max_length=255, verbose_name='Расположение места')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusName', models.CharField(max_length=255, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Terminals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminalName', models.CharField(max_length=255, verbose_name='Терминал')),
            ],
            options={
                'verbose_name': 'Терминал',
                'verbose_name_plural': 'Терминалы',
            },
        ),
        migrations.CreateModel(
            name='TypeAirplanes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=255, verbose_name='Название модели')),
                ('imgAirplane', models.ImageField(upload_to='type Airplanes', verbose_name='Фотография самолета')),
            ],
            options={
                'verbose_name': 'Модель самолета',
                'verbose_name_plural': 'Модели самолетов',
            },
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('timeWork', models.CharField(max_length=255, verbose_name='Время работы')),
                ('imgPoster', models.ImageField(upload_to='shops', verbose_name='Фото')),
                ('id_place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.places', verbose_name='Место')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('timeWork', models.CharField(max_length=255, verbose_name='Время работы')),
                ('imgPoster', models.ImageField(upload_to='foods', verbose_name='Фото')),
                ('id_place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.places', verbose_name='Место')),
            ],
            options={
                'verbose_name': 'Еда',
                'verbose_name_plural': 'Еда',
            },
        ),
        migrations.CreateModel(
            name='Airplanes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduledDateDep', models.DateField(verbose_name='Запланированная дата вылета')),
                ('scheduledTimeDep', models.TimeField(verbose_name='Запланированная время вылета')),
                ('expectedDateDep', models.DateField(blank=True, null=True, verbose_name='Фактическая дата вылета')),
                ('expectedTimeDep', models.TimeField(blank=True, null=True, verbose_name='Фактическая время вылета')),
                ('scheduledDateArr', models.DateField(verbose_name='Запланированная дата прилета')),
                ('scheduledTimeArr', models.TimeField(verbose_name='Запланированная время прилета')),
                ('expectedDateArr', models.DateField(blank=True, null=True, verbose_name='Фактическая дата прилета')),
                ('expectedTimeArr', models.TimeField(blank=True, null=True, verbose_name='Фактическая время прилета')),
                ('flightNumber', models.CharField(max_length=255, verbose_name='Номер рейса')),
                ('receptionDesks', models.CharField(blank=True, max_length=255, null=True, verbose_name='Стойка(и) регистрации')),
                ('gate', models.CharField(blank=True, max_length=8, null=True, verbose_name='Выход')),
                ('id_categoryFilters', models.CharField(choices=[('ARR', 'Прибытие'), ('DEP', 'Отправление')], max_length=6, verbose_name='Фильтр')),
                ('id_airlines', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.airlines', verbose_name='Авиакомпания')),
                ('id_direction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.directions', verbose_name='Направление (аэропорт)')),
                ('id_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.status', verbose_name='Статус')),
                ('id_terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.terminals', verbose_name='Терминал')),
                ('id_typeAirplane', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.typeairplanes', verbose_name='Модель самолета')),
            ],
            options={
                'verbose_name': 'Самолет',
                'verbose_name_plural': 'Самолеты',
            },
        ),
    ]
